#!/usr/bin/env bash
# modules/performance.sh — Enigma2 settings and sysctl performance tweaks

# Idempotently sets key=value in a config file.
update_setting() {
    local file="$1" key="$2" value="$3"

    if [[ $DRY_RUN -eq 1 ]]; then
        log_dry "Set: $key=$value (in $file)"
        return 0
    fi

    if [[ ! -f "$file" ]]; then
        log_warn "File missing, creating: $file"
        mkdir -p "$(dirname "$file")"
        touch "$file"
    fi

    local current
    current="$(grep -E "^${key}=" "$file" 2>/dev/null | head -1 | cut -d= -f2- || true)"

    if [[ "$current" == "$value" ]]; then
        log_debug "$key already correct ($value)"
        return 0
    fi

    if grep -qE "^${key}=" "$file"; then
        local escaped_key escaped_value
        escaped_key="$(echo "$key" | sed 's/\./\\./g')"
        escaped_value="$(printf '%s' "$value" | sed 's/[|\\]/\\&/g')"
        sed -i "s|^${escaped_key}=.*|${key}=${escaped_value}|" "$file"
        log_ok "Updated: $key=$value (was: $current)"
    else
        echo "${key}=${value}" >> "$file"
        log_ok "Added: $key=$value"
    fi
    ((CONFIG_CHANGES++))
}

# Computes a network buffer size proportional to available RAM.
# Clamped between 256 KB and 1 MB to avoid exhausting memory on small devices.
_compute_net_buf() {
    local ram_mb
    ram_mb="$(get_total_ram_mb)"
    local buf=$(( ram_mb * 1024 * 1024 / 32 ))
    [[ $buf -lt 262144  ]] && buf=262144
    [[ $buf -gt 1048576 ]] && buf=1048576
    echo "$buf"
}

mod_apply_performance_tweaks() {
    [[ $SKIP_PERFORMANCE -eq 1 ]] && { log_info "Performance tweaks skipped"; return 0; }
    log_step "Performance Optimizations"

    if [[ $DRY_RUN -eq 0 ]] && [[ -f "$E2_SETTINGS" ]]; then
        log_info "Stopping Enigma2 (init 4)..."
        init 4
        sleep 5
    fi

    log_info "Applying Enigma2 settings..."
    for entry in "${E2_SETTING_OVERRIDES[@]}"; do
        local key="${entry%%|*}"
        local value="${entry#*|}"
        update_setting "$E2_SETTINGS" "$key" "$value"
    done

    log_info "Applying sysctl performance settings..."
    local ram_mb net_buf
    ram_mb="$(get_total_ram_mb)"
    net_buf="$(_compute_net_buf)"
    log_info "RAM: ${ram_mb}MB — network buffers: $(( net_buf / 1024 ))KB"

    if [[ $DRY_RUN -eq 0 ]]; then
        {
            echo "# Generated by e2-setup.sh v${SCRIPT_VERSION}"
            echo "# Date: $(date)"
            echo "# Device RAM: ${ram_mb}MB"
            for tweak in "${SYSCTL_TWEAKS[@]}"; do echo "$tweak"; done
            echo "net.core.rmem_max=${net_buf}"
            echo "net.core.wmem_max=${net_buf}"
        } > "$SYSCTL_DROPIN"

        if has_command sysctl; then
            sysctl -p "$SYSCTL_DROPIN" >/dev/null 2>&1 \
                && log_ok "Sysctl settings active" \
                || log_warn "Sysctl could not be applied now (will activate on reboot)"
        fi
        log_ok "Sysctl drop-in: $SYSCTL_DROPIN"
        ((CONFIG_CHANGES++))
    else
        log_dry "Sysctl drop-in: $SYSCTL_DROPIN"
        log_dry "net.core.rmem_max=${net_buf} (RAM-aware)"
        log_dry "net.core.wmem_max=${net_buf} (RAM-aware)"
    fi

    if [[ $DRY_RUN -eq 0 ]] && [[ -f "$E2_SETTINGS" ]]; then
        log_info "Starting Enigma2 (init 3)..."
        init 3
    fi
}
